# SPDX-License-Identifier: GPL-2.0
#
# Makefile for secure hypervisor module: common
#

# Add -fno-stack-protector flag for all files in s-visor directory
ccflags-y := -fno-stack-protector
asflags-y := -fno-stack-protector

obj-y += aarch64/misc.o
obj-y += aarch64/ticket-lock.o
obj-y += aarch64/list.o
